name: app_web_deploy

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: kotlinUpgradeYarnLock
        run: ./gradlew kotlinUpgradeYarnLock

      - name: Build web app
        run: ./gradlew :example:composeApp:assemble

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'composeApp/build/dist/wasmJs/productionExecutable'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4